### PR TITLE
create_function has been DEPRECATED as of PHP 7.2.0

### PR DESCRIPTION
**Pull request by harikt**
Fix for https://www.php.net/create_function

### CODE REVIEW

**Comment by pdt256** [comment]
Thanks for the PR!

Can you please update the travis config to use a more recent version of PHP? That should fix the tests and allow me to merge.

https://github.com/pdt256/shipping/blob/190b1d74c9573e66c5359350a70054d84d7436c9/.travis.yml#L3

**Comment by harikt** [comment]
Hey @pdt256 , 

That was fast. I have updated the travis, but I believe there are some other issues that need to be addressed.

**Comment by pdt256** [comment]
I can take a look tomorrow. Hopefully we can get a release out that supports PHP 7+

Feel free to update this PR if you get to it first.

**Comment by pdt256** [comment]
I upgraded master to PHP 7.1.

Please fix the PSR-2 issues and this should be good to merge:
https://travis-ci.org/pdt256/shipping/jobs/623547060#L265

You can verify it works with:
```
vendor/bin/phpcs --standard=PSR2 src/ tests/
```

**Comment by harikt** [comment]
Hey @pdt256 ,

I have updated the tests, and composer dependencies to make sure all is green.

**Pull request merged**
